### ISSUE TITLE
dm_tempo_diario: relacionamento

### ISSUE THREAD

**Issue by Andrelamor** [transparencia-mg/servidores#3]
é necessário incluir as foreignKeys no `schema_v1.yaml`, conforme modelo abaixo

**Comment by Andrelamor** [comment]
````
foreignKeys:
  - fields:
      - id_tempo
    reference:
      fields:
        - id_tempo
      resource: dm_tempo_diario
````
